In [1]:
#Imports

import MDAnalysis as mda
from MDAnalysis.analysis import distances
from MDAnalysis.analysis import contacts

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Create Universe and lists

tt = mda.Universe("md.tpr","equilibration.gro")
FAD_lista = list(tt.atoms.types[901:923])
proteína_lista = list(tt.atoms.types[0:901])

In [5]:
#Getting a list of lists with sigma values

lista_de_listas = []

for a in FAD_lista:
    lista_pequena = []
    for b in proteína_lista:
        if a[0] == "S" and b[0] == "S":
            lista_pequena.append(0.41)
        elif (a[0] == "S" and b[0] == "T") or (a[0] == "T" and b[0] == "S"):
            lista_pequena.append(0.365)
        elif a[0] == "T" and b[0] == "T":
            lista_pequena.append(0.34)
        elif (a[0] != "S" and a[0] != "T") and (b[0] != "S" and b[0] != "T"):
            lista_pequena.append(0.47)
        elif (a[0] == "S" and (b[0] != "S" and b[0] != "T")) or ((a[0] != "S" and a[0] != "T") and b[0] == "S"):
            lista_pequena.append(0.43)
        elif (a[0] == "T" and (b[0] != "S" and b[0] != "T")) or ((a[0] != "S" and a[0] != "T") and b[0] == "T"):
            lista_pequena.append(0.395)
        else:
            lista_pequena.append(0.0)
    lista_de_listas.append(lista_pequena)
    
lista_array = np.array(lista_de_listas)            

In [7]:
#Creating the distances array that comes from the CG structure from Martinize2

FAD = tt.select_atoms("resname FAD")
protein = tt.select_atoms("name BB SC1 SC2 SC3 SC4 SC5")
distância = mda.analysis.distances.distance_array(FAD.positions, protein.positions)

In [9]:
#Distances below 0.5 nm from which we chose some to be bonds to keep FAD inside the structure (first array - FAD indexes, second array - protein indexes)

np.where(distância <= 5.0)

(array([ 0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  2,  2,  2,  2,  2,
         3,  3,  3,  3,  3,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  6,  6,
         6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  9,  9,
         9, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 12, 12,
        12, 12, 12, 13, 13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 16, 16,
        16, 16, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19, 19,
        19, 20, 20, 20, 21, 21]),
 array([ 17,  73,  74,  75,  76,  77, 187, 246,  71,  73, 186, 187, 184,
        186, 187, 188, 247, 184, 186, 187, 188, 605,  76,  77, 246,  73,
         75,  76, 186, 187, 246, 247,  17,  18,  20,  74,  77, 245, 246,
         17,  18,  73,  74,  75,  76,  20,  90,  93, 248,  20,  24, 248,
         22,  24,  25,  99, 679, 712, 721,  24,  25,  99, 250, 710, 711,
        712,  99, 382, 710, 711, 712, 382, 710, 712, 713, 714, 715, 717,
        101, 715, 846, 853, 855, 100, 101, 389, 846, 100, 110, 111, 291,

In [11]:
#Distances below the sigma value that had to be excluded (in Angstrom units)

np.where(lista_array >= distância/10)

(array([ 0,  0,  0,  1,  2,  2,  3,  4,  5,  6,  7,  7,  9, 10, 10, 11, 11,
        16, 17, 18]),
 array([ 73,  74,  76, 187, 186, 187, 186,  76, 187, 246,  73,  74,  24,
         24, 712,  99, 712, 100, 389, 384]))